Elite4_Hoenn_2_MapScripts::
	.byte 0


Elite4_Hoenn_2_EventScript_MegaAbsol::
# 6 "data/maps/Elite4_Hoenn_2/scripts.pory"
	trainerbattle_single TRAINER_MEGAABSOL, Elite4_Hoenn_2_EventScript_MegaAbsol_Text_0, Elite4_Hoenn_2_EventScript_MegaAbsol_Text_0
# 7 "data/maps/Elite4_Hoenn_2/scripts.pory"
	msgbox Elite4_Hoenn_2_EventScript_MegaAbsol_Text_0, MSGBOX_AUTOCLOSE
# 8 "data/maps/Elite4_Hoenn_2/scripts.pory"
	waitmessage
	end


Elite4_Hoenn_2_EventScript_MegaSableye::
# 15 "data/maps/Elite4_Hoenn_2/scripts.pory"
	trainerbattle_single TRAINER_MEGASABLEYE, Elite4_Hoenn_2_EventScript_MegaAbsol_Text_0, Elite4_Hoenn_2_EventScript_MegaAbsol_Text_0
# 16 "data/maps/Elite4_Hoenn_2/scripts.pory"
	msgbox Elite4_Hoenn_2_EventScript_MegaAbsol_Text_0, MSGBOX_AUTOCLOSE
# 17 "data/maps/Elite4_Hoenn_2/scripts.pory"
	waitmessage
	end


Elite4_Hoenn_2_EventScript_MegaGlalie::
# 24 "data/maps/Elite4_Hoenn_2/scripts.pory"
	trainerbattle_single TRAINER_MEGAGLALIE, Elite4_Hoenn_2_EventScript_MegaAbsol_Text_0, Elite4_Hoenn_2_EventScript_MegaAbsol_Text_0
# 25 "data/maps/Elite4_Hoenn_2/scripts.pory"
	msgbox Elite4_Hoenn_2_EventScript_MegaAbsol_Text_0, MSGBOX_AUTOCLOSE
# 26 "data/maps/Elite4_Hoenn_2/scripts.pory"
	waitmessage
	end


Elite4_Hoenn_2_EventScript_MegaSalamence::
# 33 "data/maps/Elite4_Hoenn_2/scripts.pory"
	trainerbattle_single TRAINER_MEGASALAMENCE, Elite4_Hoenn_2_EventScript_MegaAbsol_Text_0, Elite4_Hoenn_2_EventScript_MegaAbsol_Text_0
# 34 "data/maps/Elite4_Hoenn_2/scripts.pory"
	msgbox Elite4_Hoenn_2_EventScript_MegaAbsol_Text_0, MSGBOX_AUTOCLOSE
# 35 "data/maps/Elite4_Hoenn_2/scripts.pory"
	waitmessage
	end


Elite4_Hoenn_2_EventScript_MegaSwampert::
# 42 "data/maps/Elite4_Hoenn_2/scripts.pory"
	trainerbattle_single TRAINER_MEGASWAMPERT, Elite4_Hoenn_2_EventScript_MegaAbsol_Text_0, Elite4_Hoenn_2_EventScript_MegaAbsol_Text_0
# 43 "data/maps/Elite4_Hoenn_2/scripts.pory"
	msgbox Elite4_Hoenn_2_EventScript_MegaAbsol_Text_0, MSGBOX_AUTOCLOSE
# 44 "data/maps/Elite4_Hoenn_2/scripts.pory"
	waitmessage
	end


Elite4_Hoenn_2_EventScript_MegaAbsol_Text_0:
# 6 "data/maps/Elite4_Hoenn_2/scripts.pory"
	.string "test.$"
