Hoenn3_5_MapScripts::
	.byte 0


Hoenn3_5_Cradily::
# 5 "data/maps/Hoenn3_5/scripts.pory"
	trainerbattle_single TRAINER_CRADILY, Hoenn3_5_Cradily_Text_0, Hoenn3_5_Cradily_Text_0
# 6 "data/maps/Hoenn3_5/scripts.pory"
	msgbox Hoenn3_5_Cradily_Text_0, MSGBOX_AUTOCLOSE
# 7 "data/maps/Hoenn3_5/scripts.pory"
	waitmessage
	end


Hoenn3_5_Armaldo::
# 12 "data/maps/Hoenn3_5/scripts.pory"
	trainerbattle_single TRAINER_ARMALDO, Hoenn3_5_Cradily_Text_0, Hoenn3_5_Cradily_Text_0
# 13 "data/maps/Hoenn3_5/scripts.pory"
	msgbox Hoenn3_5_Cradily_Text_0, MSGBOX_AUTOCLOSE
# 14 "data/maps/Hoenn3_5/scripts.pory"
	waitmessage
	end


Hoenn3_5_Linoone::
# 19 "data/maps/Hoenn3_5/scripts.pory"
	trainerbattle_single TRAINER_LINOONE, Hoenn3_5_Cradily_Text_0, Hoenn3_5_Cradily_Text_0
# 20 "data/maps/Hoenn3_5/scripts.pory"
	msgbox Hoenn3_5_Cradily_Text_0, MSGBOX_AUTOCLOSE
# 21 "data/maps/Hoenn3_5/scripts.pory"
	waitmessage
	end


Hoenn3_5_Cradily_Text_0:
# 5 "data/maps/Hoenn3_5/scripts.pory"
	.string "test$"
