gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "$"

gText_Birch_NuzlockeChallenge::
	.string "Oh, before we begin…\n"
	.string "There’s something new I’ve been\l"
	.string "researching.\p"
	.string "$"

gText_Birch_NoNuzlocke::
	.string "That’s quite all right!\p"
	.string "There’s no shame in taking your\n"
	.string "journey at your own pace.\p"
	.string "I’ll leave the NUZLOCKE CHALLENGE\n"
	.string "disabled.\p"
	.string "If you decide you want to take on\n"
	.string "the challenge, you'll need to start\l"
	.string "a new game.\p"
	.string "$"

gText_Birch_YesNuzlocke::
	.string "I see!\n"
	.string "You’re looking for a real challenge!\p"
	.string "$"

gText_Birch_Farewell::
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
