Hoenn3_1_MapScripts::
	.byte 0


Hoenn3_1_Vibrava::
# 5 "data/maps/Hoenn3_1/scripts.pory"
	trainerbattle_single TRAINER_VIBRAVA, Hoenn3_1_Vibrava_Text_0, Hoenn3_1_Vibrava_Text_0
# 6 "data/maps/Hoenn3_1/scripts.pory"
	msgbox Hoenn3_1_Vibrava_Text_0, MSGBOX_AUTOCLOSE
# 7 "data/maps/Hoenn3_1/scripts.pory"
	waitmessage
	end


Hoenn3_1_Cacturne::
# 12 "data/maps/Hoenn3_1/scripts.pory"
	trainerbattle_single TRAINER_CACTURNE, Hoenn3_1_Vibrava_Text_0, Hoenn3_1_Vibrava_Text_0
# 13 "data/maps/Hoenn3_1/scripts.pory"
	msgbox Hoenn3_1_Vibrava_Text_0, MSGBOX_AUTOCLOSE
# 14 "data/maps/Hoenn3_1/scripts.pory"
	waitmessage
	end


Hoenn3_1_Claydol::
# 19 "data/maps/Hoenn3_1/scripts.pory"
	trainerbattle_single TRAINER_CLAYDOL, Hoenn3_1_Vibrava_Text_0, Hoenn3_1_Vibrava_Text_0
# 20 "data/maps/Hoenn3_1/scripts.pory"
	msgbox Hoenn3_1_Vibrava_Text_0, MSGBOX_AUTOCLOSE
# 21 "data/maps/Hoenn3_1/scripts.pory"
	waitmessage
	end


Hoenn3_1_Vibrava_Text_0:
# 5 "data/maps/Hoenn3_1/scripts.pory"
	.string "test$"
