Hoenn4_3_MapScripts::
	.byte 0


Hoenn4_3_Lanturn::
# 5 "data/maps/Hoenn4_3/scripts.pory"
	trainerbattle_single TRAINER_LANTURN, Hoenn4_3_Lanturn_Text_0, Hoenn4_3_Lanturn_Text_0
# 6 "data/maps/Hoenn4_3/scripts.pory"
	msgbox Hoenn4_3_Lanturn_Text_0, MSGBOX_AUTOCLOSE
# 7 "data/maps/Hoenn4_3/scripts.pory"
	waitmessage
	end


Hoenn4_3_Starmie::
# 11 "data/maps/Hoenn4_3/scripts.pory"
	trainerbattle_single TRAINER_STARMIE, Hoenn4_3_Lanturn_Text_0, Hoenn4_3_Lanturn_Text_0
# 12 "data/maps/Hoenn4_3/scripts.pory"
	msgbox Hoenn4_3_Lanturn_Text_0, MSGBOX_AUTOCLOSE
# 13 "data/maps/Hoenn4_3/scripts.pory"
	waitmessage
	end


Hoenn4_3_Slowbro::
# 17 "data/maps/Hoenn4_3/scripts.pory"
	trainerbattle_single TRAINER_SLOWBRO, Hoenn4_3_Lanturn_Text_0, Hoenn4_3_Lanturn_Text_0
# 18 "data/maps/Hoenn4_3/scripts.pory"
	msgbox Hoenn4_3_Lanturn_Text_0, MSGBOX_AUTOCLOSE
# 19 "data/maps/Hoenn4_3/scripts.pory"
	waitmessage
	end


Hoenn4_3_Heracross::
# 23 "data/maps/Hoenn4_3/scripts.pory"
	trainerbattle_single TRAINER_HERACROSS, Hoenn4_3_Lanturn_Text_0, Hoenn4_3_Lanturn_Text_0
# 24 "data/maps/Hoenn4_3/scripts.pory"
	msgbox Hoenn4_3_Lanturn_Text_0, MSGBOX_AUTOCLOSE
# 25 "data/maps/Hoenn4_3/scripts.pory"
	waitmessage
	end


Hoenn4_3_Pinsir::
# 29 "data/maps/Hoenn4_3/scripts.pory"
	trainerbattle_single TRAINER_PINSIR, Hoenn4_3_Lanturn_Text_0, Hoenn4_3_Lanturn_Text_0
# 30 "data/maps/Hoenn4_3/scripts.pory"
	msgbox Hoenn4_3_Lanturn_Text_0, MSGBOX_AUTOCLOSE
# 31 "data/maps/Hoenn4_3/scripts.pory"
	waitmessage
	end


Hoenn4_3_Lanturn_Text_0:
# 5 "data/maps/Hoenn4_3/scripts.pory"
	.string "test$"
