Hoenn3_1_House_MapScripts::
	.byte 0


Hoenn3_Itemball_1::
# 5 "data/maps/Hoenn3_1_House/scripts.pory"
	lockall
# 6 "data/maps/Hoenn3_1_House/scripts.pory"
	call GiveCommonItem
# 7 "data/maps/Hoenn3_1_House/scripts.pory"
	removeobject Hoenn3_Ball1
# 8 "data/maps/Hoenn3_1_House/scripts.pory"
	setflag FLAG_ITEM_3_1
# 9 "data/maps/Hoenn3_1_House/scripts.pory"
	releaseall
	end


Hoenn3_Itemball_2::
# 14 "data/maps/Hoenn3_1_House/scripts.pory"
	lockall
# 15 "data/maps/Hoenn3_1_House/scripts.pory"
	call GiveUncommonItem
# 16 "data/maps/Hoenn3_1_House/scripts.pory"
	removeobject Hoenn3_Ball2
# 17 "data/maps/Hoenn3_1_House/scripts.pory"
	setflag FLAG_ITEM_3_2
# 18 "data/maps/Hoenn3_1_House/scripts.pory"
	releaseall
	end


Hoenn3_Itemball_3::
# 23 "data/maps/Hoenn3_1_House/scripts.pory"
	lockall
# 24 "data/maps/Hoenn3_1_House/scripts.pory"
	call GiveRareItem
# 25 "data/maps/Hoenn3_1_House/scripts.pory"
	removeobject Hoenn3_Ball3
# 26 "data/maps/Hoenn3_1_House/scripts.pory"
	setflag FLAG_ITEM_3_3
# 27 "data/maps/Hoenn3_1_House/scripts.pory"
	releaseall
	end


Hoenn3_Itemball_4::
# 32 "data/maps/Hoenn3_1_House/scripts.pory"
	lockall
# 33 "data/maps/Hoenn3_1_House/scripts.pory"
	call GiveUncommonItem
# 34 "data/maps/Hoenn3_1_House/scripts.pory"
	removeobject Hoenn3_Ball4
# 35 "data/maps/Hoenn3_1_House/scripts.pory"
	setflag FLAG_ITEM_3_4
# 36 "data/maps/Hoenn3_1_House/scripts.pory"
	releaseall
	end


Hoenn3_Itemball_5::
# 41 "data/maps/Hoenn3_1_House/scripts.pory"
	lockall
# 42 "data/maps/Hoenn3_1_House/scripts.pory"
	call GiveCommonItem
# 43 "data/maps/Hoenn3_1_House/scripts.pory"
	removeobject Hoenn3_Ball5
# 44 "data/maps/Hoenn3_1_House/scripts.pory"
	setflag FLAG_ITEM_3_5
# 45 "data/maps/Hoenn3_1_House/scripts.pory"
	releaseall
	end

