"""Generates trainer front-pic data for Pokemon species referenced in
`Pic:` fields of the various src/data/*.party files.

Normally `Pic: <Name>` in a .party file must match an existing trainer
sprite constant (TRAINER_PIC_FRONT_<NAME>), e.g. `Pic: Hiker`. This
script lets you instead write a Pokemon species name, e.g. `Pic: Wingull`,
and will automatically:
  - crop that species' animated front sprite (graphics/pokemon/<species>/
    anim_front.png, which stores 2 stacked animation frames) down to just
    its first frame,
  - save it under graphics/trainers/front_pics/pkmn_<species>.png,
  - and emit the generated constants/INCBIN/table entries needed to wire
    it up as TRAINER_PIC_FRONT_<SPECIES>.

Mega Evolutions are also supported: `Pic: Absol-Mega` (or "Absol Mega")
uses graphics/pokemon/absol/mega/front.png directly (already a single
static frame, so no cropping is needed), and `Pic: Charizard-Mega-X` /
`Pic: Charizard-Mega-Y` use the mega_x/mega_y subfolders.

Run this whenever a .party file's `Pic:` fields change. It's also safe
to run any time; it only re-crops sprites that are missing or stale, and
regenerates the content it owns:
  - the enum entries spliced directly into include/constants/trainers.h
    (between GENERATED_PKMN_TRAINER_PICS_BEGIN/END markers -- this can't
    be a plain #include because tools/preproc's enum parser, used to
    convert this enum for asm files, chokes on #include inside an enum)
  - src/data/graphics/trainers_pkmn_pics.h
  - src/data/graphics/trainers_pkmn_pics_sprites.h
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
from png_utils import crop_top_half  # noqa: E402

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))

PARTY_FILES = [
    "src/data/trainers.party",
    "src/data/trainers_frlg.party",
    "src/data/debug_trainers.party",
    "src/data/battle_partners.party",
]

TRAINERS_CONSTANTS_H = "include/constants/trainers.h"
ENUM_MARKER_BEGIN = "// GENERATED_PKMN_TRAINER_PICS_BEGIN"
ENUM_MARKER_END = "// GENERATED_PKMN_TRAINER_PICS_END"
GENERATED_INCBIN_H = "src/data/graphics/trainers_pkmn_pics.h"
GENERATED_SPRITES_H = "src/data/graphics/trainers_pkmn_pics_sprites.h"
FRONT_PICS_DIR = "graphics/trainers/front_pics"
POKEMON_GFX_DIR = "graphics/pokemon"

MEGA_RE = re.compile(r"^(.*?)[-\s]+Mega(?:[-\s]+([XY]))?$", re.IGNORECASE)

GENERATED_HEADER_COMMENT = (
    "// Auto-generated by tools/pkmn_trainer_pics/generate.py - do not edit by hand.\n"
)


def path(*parts):
    return os.path.join(ROOT, *parts)


def to_const_suffix(name):
    """'Wingull' -> 'WINGULL', 'Ho-Oh' -> 'HO_OH'."""
    s = re.sub(r"[^A-Za-z0-9]+", "_", name.strip()).strip("_")
    return s.upper()


def to_species_folder(name):
    """'Mr. Mime' -> 'mr_mime', "Farfetch'd" -> 'farfetchd'."""
    s = name.strip().lower().replace("'", "")
    s = re.sub(r"[^a-z0-9]+", "_", s).strip("_")
    return s


def to_pascal_case(folder_name):
    return "".join(part.capitalize() for part in folder_name.split("_"))


def resolve_pic_source(pic_name):
    """Figures out where the sprite for a `Pic:` species name lives.

    Returns a dict with either:
      {"kind": "mega", "front_png": <abs path>, "incbin_front": <rel path
       stem>, "incbin_pal": <rel path>}
    or:
      {"kind": "normal", "species_folder": <folder name>}
    """
    mega_match = MEGA_RE.match(pic_name.strip())
    if mega_match:
        base_folder = to_species_folder(mega_match.group(1))
        xy = mega_match.group(2)
        mega_dir = f"mega_{xy.lower()}" if xy else "mega"
        front_png = path(POKEMON_GFX_DIR, base_folder, mega_dir, "front.png")
        if os.path.isfile(front_png):
            gfx_rel = f"{POKEMON_GFX_DIR}/{base_folder}/{mega_dir}"
            return {
                "kind": "mega",
                "front_png": front_png,
                "incbin_front": f"{gfx_rel}/front.4bpp.smol",
                "incbin_pal": f"{gfx_rel}/normal.gbapal",
            }
    return {"kind": "normal", "species_folder": to_species_folder(pic_name)}


def get_existing_trainer_pic_constants():
    with open(path(TRAINERS_CONSTANTS_H), encoding="utf-8") as f:
        text = f.read()
    # Exclude our own generated splice so previously-generated Pokemon
    # constants aren't mistaken for pre-existing trainer-class sprites.
    begin = text.find(ENUM_MARKER_BEGIN)
    end = text.find(ENUM_MARKER_END)
    if begin != -1 and end != -1:
        text = text[:begin] + text[end + len(ENUM_MARKER_END):]
    return set(re.findall(r"\bTRAINER_PIC_FRONT_([A-Z0-9_]+)\b", text))


def get_pic_names_from_party_files():
    names = []
    for rel_path in PARTY_FILES:
        full_path = path(rel_path)
        if not os.path.isfile(full_path):
            continue
        with open(full_path, encoding="utf-8") as f:
            for line in f:
                match = re.match(r"\s*Pic:\s*(.+?)\s*$", line)
                if match:
                    names.append(match.group(1))
    return names


def update_enum_splice(entries):
    trainers_h = path(TRAINERS_CONSTANTS_H)
    with open(trainers_h, encoding="utf-8") as f:
        text = f.read()

    begin = text.index(ENUM_MARKER_BEGIN)
    end = text.index(ENUM_MARKER_END, begin) + len(ENUM_MARKER_END)
    lines = [ENUM_MARKER_BEGIN]
    for entry in entries:
        lines.append(f"    TRAINER_PIC_FRONT_{entry['suffix']},")
    lines.append(f"    {ENUM_MARKER_END}")
    text = text[:begin] + "\n".join(lines) + text[end:]

    with open(trainers_h, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def main():
    existing_constants = get_existing_trainer_pic_constants()
    candidates = {}  # const_suffix -> original Pic: name
    for pic_name in get_pic_names_from_party_files():
        suffix = to_const_suffix(pic_name)
        if not suffix or suffix in existing_constants:
            continue  # matches a real (non-Pokemon) trainer sprite already
        candidates[suffix] = pic_name.strip()

    entries = []
    for suffix, pic_name in sorted(candidates.items()):
        source = resolve_pic_source(pic_name)
        pascal = to_pascal_case(suffix.lower())

        if source["kind"] == "mega":
            entries.append({
                "suffix": suffix,
                "pascal": pascal,
                "incbin_front": source["incbin_front"],
                "incbin_pal": source["incbin_pal"],
            })
            continue

        species_folder = source["species_folder"]
        src_png = path(POKEMON_GFX_DIR, species_folder, "anim_front.png")
        if not os.path.isfile(src_png):
            print(f"warning: Pic '{suffix}' looks like a Pokemon name, but "
                  f"{os.path.relpath(src_png, ROOT)} doesn't exist; skipping.",
                  file=sys.stderr)
            continue

        dst_png = path(FRONT_PICS_DIR, f"pkmn_{species_folder}.png")
        if not os.path.isfile(dst_png) or os.path.getmtime(src_png) > os.path.getmtime(dst_png):
            os.makedirs(os.path.dirname(dst_png), exist_ok=True)
            crop_top_half(src_png, dst_png)
            print(f"generated {os.path.relpath(dst_png, ROOT)}")

        entries.append({
            "suffix": suffix,
            "pascal": pascal,
            "incbin_front": f"{FRONT_PICS_DIR}/pkmn_{species_folder}.4bpp.smol",
            "incbin_pal": f"{FRONT_PICS_DIR}/pkmn_{species_folder}.gbapal",
        })

    update_enum_splice(entries)

    with open(path(GENERATED_INCBIN_H), "w", encoding="utf-8", newline="\n") as f:
        f.write(GENERATED_HEADER_COMMENT)
        for entry in entries:
            pascal = entry["pascal"]
            f.write(f'const u32 gTrainerFrontPic_Pkmn{pascal}[] = '
                    f'INCBIN_U32("{entry["incbin_front"]}");\n')
            f.write(f'const u16 gTrainerPalette_Pkmn{pascal}[] = '
                    f'INCBIN_U16("{entry["incbin_pal"]}");\n')

    with open(path(GENERATED_SPRITES_H), "w", encoding="utf-8", newline="\n") as f:
        f.write(GENERATED_HEADER_COMMENT)
        for entry in entries:
            pascal = entry["pascal"]
            f.write(f"    TRAINER_SPRITE(TRAINER_PIC_FRONT_{entry['suffix']}, "
                    f"gTrainerFrontPic_Pkmn{pascal}, gTrainerPalette_Pkmn{pascal}),\n")

    print(f"{len(entries)} Pokemon trainer pic(s) registered.")


if __name__ == "__main__":
    main()

