Hoenn4_2_MapScripts::
	.byte 0


Hoenn4_2_Golduck::
# 5 "data/maps/Hoenn4_2/scripts.pory"
	trainerbattle_single TRAINER_GOLDUCK, Hoenn4_2_Golduck_Text_0, Hoenn4_2_Golduck_Text_0
# 6 "data/maps/Hoenn4_2/scripts.pory"
	msgbox Hoenn4_2_Golduck_Text_0, MSGBOX_AUTOCLOSE
# 7 "data/maps/Hoenn4_2/scripts.pory"
	waitmessage
	end


Hoenn4_2_Wobbuffet::
# 12 "data/maps/Hoenn4_2/scripts.pory"
	trainerbattle_single TRAINER_WOBBUFFET, Hoenn4_2_Golduck_Text_0, Hoenn4_2_Golduck_Text_0
# 13 "data/maps/Hoenn4_2/scripts.pory"
	msgbox Hoenn4_2_Golduck_Text_0, MSGBOX_AUTOCLOSE
# 14 "data/maps/Hoenn4_2/scripts.pory"
	waitmessage
	end


Hoenn4_2_Ludicolo::
# 19 "data/maps/Hoenn4_2/scripts.pory"
	trainerbattle_single TRAINER_LUDICOLO, Hoenn4_2_Golduck_Text_0, Hoenn4_2_Golduck_Text_0
# 20 "data/maps/Hoenn4_2/scripts.pory"
	msgbox Hoenn4_2_Golduck_Text_0, MSGBOX_AUTOCLOSE
# 21 "data/maps/Hoenn4_2/scripts.pory"
	waitmessage
	end


Hoenn4_2_Vileplume::
# 26 "data/maps/Hoenn4_2/scripts.pory"
	trainerbattle_single TRAINER_VILEPLUME, Hoenn4_2_Golduck_Text_0, Hoenn4_2_Golduck_Text_0
# 27 "data/maps/Hoenn4_2/scripts.pory"
	msgbox Hoenn4_2_Golduck_Text_0, MSGBOX_AUTOCLOSE
# 28 "data/maps/Hoenn4_2/scripts.pory"
	waitmessage
	end


Hoenn4_2_Xatu::
# 33 "data/maps/Hoenn4_2/scripts.pory"
	trainerbattle_single TRAINER_XATU, Hoenn4_2_Golduck_Text_0, Hoenn4_2_Golduck_Text_0
# 34 "data/maps/Hoenn4_2/scripts.pory"
	msgbox Hoenn4_2_Golduck_Text_0, MSGBOX_AUTOCLOSE
# 35 "data/maps/Hoenn4_2/scripts.pory"
	waitmessage
	end


Hoenn4_2_Glalie::
# 40 "data/maps/Hoenn4_2/scripts.pory"
	trainerbattle_single TRAINER_GLALIE, Hoenn4_2_Golduck_Text_0, Hoenn4_2_Golduck_Text_0
# 41 "data/maps/Hoenn4_2/scripts.pory"
	msgbox Hoenn4_2_Golduck_Text_0, MSGBOX_AUTOCLOSE
# 42 "data/maps/Hoenn4_2/scripts.pory"
	waitmessage
	end


Hoenn4_2_Golduck_Text_0:
# 5 "data/maps/Hoenn4_2/scripts.pory"
	.string "test$"
